### ISSUE TITLE
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalStateException: No Driver has been registered with name, com.mysql.cj.jdbc.Driver. Please check your system properties or secretsmanager.properties for typos. Also ensure that the Driver registers itself.

### ISSUE THREAD

**Issue by Vahinvishnu** [aws/aws-secretsmanager-jdbc#62] opened 2021-12-02 11:48 UTC
Cant able to pass the secrets in the spring boot application. facing the error below.

Error : Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalStateException: No Driver has been registered with name, com.mysql.cj.jdbc.Driver. Please check your system properties or secretsmanager.properties for typos. Also ensure that the Driver registers itself.

But i am able to run the application using the password hardcoded. With the secrets manager arn it cant bale to connect.

Below is my application.properties files and pom.xml file.

spring.datasource.url=jdbc-secretsmanager:mysql://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:3350/jdoc?useSSL=false
spring.datasource.username=XXXXXXXXXXXXXXXXXXXXXXXXXX
spring.datasource.driver-class-name=com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver

Dependency file has been updated

just add mysql and jdbc dependencies like below

<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jdbc</artifactId>
</dependency>

**Comment by jbct** [comment] 2022-11-14 19:54
Closing as a duplicate of https://github.com/aws/aws-secretsmanager-jdbc/issues/44 - plan to work the "No Drive has been registered with name" issues together.

**Closed by jbct** 2022-11-14 19:54 UTC
Labels: bug
