### ISSUE TITLE
Use 2 distinct secrets 

### ISSUE THREAD

**Issue by fabiowq** [aws/aws-secretsmanager-jdbc#52] opened 2020-11-18 18:30 UTC
Hello,

Is it possible to use it with 2 distinct secrets: one for user and another for password?

username=usernameSecretId
password=passwordSecretId

Thanks.

**Comment by willtong1234** [comment] 2021-05-26 16:18
Thank you for your feedback. We have noted this as a feature request.

**Comment by willtong1234** [comment] 2021-07-08 20:52
We have reviewed this request. Support for multiple different secrets goes against our best practices. Our recommendation is to combine your username/password into a single secret and use the JDBC library as intended. This would also have cost and availability benefits. Please refer to the [readme](https://github.com/aws/aws-secretsmanager-jdbc#readme) for some examples on the secret format expected. Closing this issue, thank you for your suggestion.

**Closed by willtong1234** 2021-07-08 20:52 UTC
Labels: enhancement
