### ISSUE TITLE
AWS Secrets Manager Postgress SQL Driver not working in springboot  

### ISSUE THREAD

**Issue by salman-shezad** [aws/aws-secretsmanager-jdbc#67] opened 2022-03-11 14:14 UTC
Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Unsatisfied dependency expressed through method 'dataSourceScriptDatabaseInitializer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NoClassDefFoundError: com/amazonaws/transform/EnhancedJsonErrorUnmarshaller

<dependency>
    <groupId>com.amazonaws.secretsmanager</groupId>
    <artifactId>aws-secretsmanager-jdbc</artifactId>
    <version>1.0.7</version>
</dependency>

https://github.com/aws/aws-secretsmanager-jdbc

<img width="1337" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/97128831/157884311-c772c77e-a324-40e4-b163-040f30ebad8e.png">

**Comment by simonmarty** [comment] 2022-05-10 19:42
It doesn't look like the error is caused by this library. Can you provide some sample code to reproduce along with the dependencies you are using?

**Comment by danmancuso** [comment] 2022-09-08 17:09
Closing this ticket. @salman-shezad if you need further assistance feel free to reopen this ticket, or open a new ticket.

**Closed by danmancuso** 2022-09-08 17:09 UTC
Labels: bug
