### ISSUE TITLE
Using MySQL driver fails when using Liquibase Maven plugin

### ISSUE THREAD

**Issue by kuma-blue** [aws/aws-secretsmanager-jdbc#66] opened 2022-02-25 01:16 UTC
Trying to use the MySQL driver to grab  our secrets from AWS using the Maven Liquibase plugin and I keep getting this error:
```
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:4.7.1:status (default-cli) on project smart-is:
[ERROR] Error setting up or running Liquibase:
[ERROR] liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.lang.IllegalStateException: No Driver has been registered with name, com.mysql.cj.jdbc.Driver. Please check your system properties or secretsmanager.properties for typos. Also ensure that the Driver registers itself.
```

I went with the solution as described in Issue #47 where you write your own custom SecretsManager driver and make sure that the driver registers itself. Basically I had changed AWSSecretsManagerMySQLDriver.getDefaultDriverClass() line #132 to: 
```
 Class.forName("com.mysql.cj.jdbc.Driver", true, this.getClass().getClassLoader());
```

My Liquibase config is as follows (defined in our pom.xml):
```
	<plugin>
		<groupId>org.liquibase</groupId>
		<artifactId>liquibase-maven-plugin</artifactId>
		<version>4.7.1</version>
		<configuration>
			<driver>com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver</driver>
			<username>{AWS secrets name}</username>
			<url>jdbc-secretsmanager:mysql://{path to our DB}</url>
			<changeLogFile>{location of our changeset file}</changeLogFile>
		</configuration>
	</plugin>
```

Can someone confirm/fix this issue? Having to extend AWSSecretsManagerDriver is a hacky way of doing things...

**Comment by jbct** [comment] 2022-11-14 20:00
Closing as a duplicate of https://github.com/aws/aws-secretsmanager-jdbc/issues/44. Working all of the tickets related to "No Driver has been registered with name" together.

**Closed by jbct** 2022-11-14 20:00 UTC
Labels: bug
